// Captures bank push notifications WITHOUT a third-party dependency: a minimal
// Kotlin NotificationListenerService is written straight into the generated
// Android project and declared in the manifest. It filters to the bank apps and
// appends {title,text,pkg,time} to a JSON file in the app's filesDir. The JS side
// (src/services/bankNotificationDrain.ts) reads that file — which is the same
// location as expo-file-system's documentDirectory — on every app foreground and
// runs it through the existing ingest → queue → auto-accept pipeline.
//
// Going custom (vs react-native-android-notification-listener) avoids the stale
// module's AGP-8 `namespace` build break on SDK 54 and keeps every moving part
// under our control. The user still has to grant "Notification access" once
// (Settings button opens that system screen).
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const path = require('path');
const fs = require('fs');

const SERVICE_CLASS = 'SappNotificationListener';

// The bank apps whose notifications we capture. Keep in sync with BANK_PACKAGES in
// src/utils/bankNotification.ts.
const BANK_PACKAGES = ['pl.pekao24.peopay', 'eu.eleader.mobilebanking.pekao', 'pl.pkobp.iko'];

function kotlinSource(pkg) {
  const pkgSet = BANK_PACKAGES.map((p) => `"${p}"`).join(', ');
  return `package ${pkg}

import android.app.Notification
import android.content.ComponentName
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import org.json.JSONArray
import org.json.JSONObject
import java.io.File

// Auto-generated by plugins/withBankNotificationListener.js — do not edit here.
class ${SERVICE_CLASS} : NotificationListenerService() {

  private val bankPackages = setOf(${pkgSet})

  override fun onNotificationPosted(sbn: StatusBarNotification?) {
    handle(sbn)
  }

  // When the system (re)binds the listener — e.g. after an OEM battery-saver killed
  // it and it came back — sweep any bank notifications still in the tray so a kill
  // doesn't silently drop the ones that arrived while we were down.
  override fun onListenerConnected() {
    try {
      val active = activeNotifications ?: return
      for (sbn in active) handle(sbn)
    } catch (e: Exception) {}
  }

  // If we get unbound, politely ask the system to rebind us.
  override fun onListenerDisconnected() {
    try { requestRebind(ComponentName(this, ${SERVICE_CLASS}::class.java)) } catch (e: Exception) {}
  }

  private fun handle(sbn: StatusBarNotification?) {
    try {
      val n = sbn ?: return
      val pkg = n.packageName ?: return
      if (!bankPackages.contains(pkg)) return
      val extras = n.notification?.extras ?: return
      val title = extras.getCharSequence(Notification.EXTRA_TITLE)?.toString() ?: ""
      val text = (extras.getCharSequence(Notification.EXTRA_TEXT)
        ?: extras.getCharSequence(Notification.EXTRA_BIG_TEXT))?.toString() ?: ""
      if (title.isEmpty() && text.isEmpty()) return
      append(pkg, title, text, n.postTime)
    } catch (e: Exception) {}
  }

  @Synchronized
  private fun append(pkg: String, title: String, text: String, time: Long) {
    try {
      val file = File(filesDir, FILE_NAME)
      val arr = if (file.exists()) {
        try { JSONArray(file.readText()) } catch (e: Exception) { JSONArray() }
      } else JSONArray()
      // dedup: the reconnect sweep can re-see a notification we already stored
      for (i in 0 until arr.length()) {
        val o = arr.optJSONObject(i) ?: continue
        if (o.optLong("time") == time && o.optString("title") == title && o.optString("text") == text) return
      }
      val obj = JSONObject()
      obj.put("pkg", pkg)
      obj.put("title", title)
      obj.put("text", text)
      obj.put("time", time)
      arr.put(obj)
      val out = if (arr.length() > MAX) {
        val t = JSONArray()
        for (i in (arr.length() - MAX) until arr.length()) t.put(arr.get(i))
        t
      } else arr
      file.writeText(out.toString())
    } catch (e: Exception) {}
  }

  companion object {
    const val FILE_NAME = "bank_notifications.json"
    const val MAX = 50
  }
}
`;
}

function withServiceSource(config) {
  return withDangerousMod(config, ['android', async (cfg) => {
    const pkg = (cfg.android && cfg.android.package) || 'com.sokki.sapp';
    const javaDir = path.join(
      cfg.modRequest.platformProjectRoot,
      'app', 'src', 'main', 'java', ...pkg.split('.'),
    );
    fs.mkdirSync(javaDir, { recursive: true });
    fs.writeFileSync(path.join(javaDir, `${SERVICE_CLASS}.kt`), kotlinSource(pkg), 'utf8');
    return cfg;
  }]);
}

function withServiceManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    if (!Array.isArray(app.service)) app.service = [];
    const name = `.${SERVICE_CLASS}`;
    if (app.service.some((s) => s.$ && s.$['android:name'] === name)) return cfg;
    app.service.push({
      $: {
        'android:name': name,
        'android:label': 'Sapp — powiadomienia',
        'android:exported': 'true',
        'android:permission': 'android.permission.BIND_NOTIFICATION_LISTENER_SERVICE',
      },
      'intent-filter': [
        { action: [{ $: { 'android:name': 'android.service.notification.NotificationListenerService' } }] },
      ],
    });
    return cfg;
  });
}

module.exports = function withBankNotificationListener(config) {
  config = withServiceSource(config);
  config = withServiceManifest(config);
  return config;
};
