// Widget pulpitu Androida "Zadania" (2026-09-23, user: "bardzo lubiłem mieć na ekranie co
// muszę zrobić/kupić"). Napisany od zera jako natywny Kotlin, wpięty przez ten config-plugin —
// TEN SAM wzorzec co withBankNotificationListener.js/withNativeCrashCatcher.js (kod prosto do
// wygenerowanego projektu Androida, zero zewnętrznej zależności typu react-native-android-
// widget). Świadomy wybór: ten projekt już RAZ trafił na build-breaking problem ze stale'ym
// natywnym pakietem (namespace/AGP-8 na SDK 54, patrz komentarz w withBankNotificationListener.
// js) i od tego czasu woli trzymać proste, dobrze udokumentowane natywne API (tu:
// AppWidgetProvider/RemoteViews, stabilne od lat) pod pełną kontrolą zamiast ryzykować kolejną
// niezależną bibliotekę.
//
// Przepływ: JS (widgetSync.ts) pisze JSON snapshot do filesDir (ten sam katalog co
// bankNotificationDrain.ts) i woła natywny most `TasksWidgetModule.requestUpdate()`.
// `TasksWidgetProvider.updateAll()` czyta ten plik i renderuje do 6 stałych slotów w
// RemoteViews (RemoteViews nie wspiera list/scrolla bez RemoteViewsService — 6 slotów to
// świadomy, prostszy odpowiednik "top 5-6 zadań" z widgetSync.ts). Tap w widget → deep link
// `sapp://tasks` (schemat już zarejestrowany w app.json).
const { withAndroidManifest, withDangerousMod, withMainApplication, AndroidConfig } = require('@expo/config-plugins');
const { mergeContents } = require('@expo/config-plugins/build/utils/generateCode');
const path = require('path');
const fs = require('fs');

const PROVIDER_CLASS = 'TasksWidgetProvider';
const MODULE_CLASS = 'TasksWidgetModule';
const PACKAGE_CLASS = 'TasksWidgetPackage';
const CONFIG_CLASS = 'TasksWidgetConfigActivity';
const ROWS = 6;

function providerKotlin(pkg) {
  const rowIds = Array.from({ length: ROWS }, (_, i) => `R.id.widget_row${i}`).join(', ');
  const dotIds = Array.from({ length: ROWS }, (_, i) => `R.id.widget_dot${i}`).join(', ');
  const titleIds = Array.from({ length: ROWS }, (_, i) => `R.id.widget_title${i}`).join(', ');
  const subIds = Array.from({ length: ROWS }, (_, i) => `R.id.widget_sub${i}`).join(', ');
  return `package ${pkg}

import android.app.PendingIntent
import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.SharedPreferences
import android.graphics.Color
import android.net.Uri
import android.view.View
import android.widget.RemoteViews
import org.json.JSONArray
import java.io.File

// Auto-generated by plugins/withTasksWidget.js — do not edit here.
class ${PROVIDER_CLASS} : AppWidgetProvider() {
  override fun onUpdate(context: Context, appWidgetManager: AppWidgetManager, appWidgetIds: IntArray) {
    for (id in appWidgetIds) updateOne(context, id)
  }

  // Sprząta ustawienie przezroczystości usuniętego widgetu — nie zostawiać martwych kluczy w
  // SharedPreferences (jeden widget instance zwykle w praktyce, ale kontrakt Androida
  // dopuszcza wiele naraz).
  override fun onDeleted(context: Context, appWidgetIds: IntArray) {
    val prefs = prefs(context)
    val editor = prefs.edit()
    for (id in appWidgetIds) editor.remove(PREF_TRANSPARENT_PREFIX + id)
    editor.apply()
  }

  companion object {
    const val PREFS_NAME = "TasksWidgetPrefs"
    const val PREF_TRANSPARENT_PREFIX = "transparent_"
    private const val ROWS = ${ROWS}
    private val ROW_IDS = intArrayOf(${rowIds})
    private val DOT_IDS = intArrayOf(${dotIds})
    private val TITLE_IDS = intArrayOf(${titleIds})
    private val SUB_IDS = intArrayOf(${subIds})

    fun prefs(context: Context): SharedPreferences =
      context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    // Woła się po każdej zmianie danych (JS bridge) — te same widoki dla wszystkich instancji,
    // ale ustawienie przezroczystości jest PER instancję (buildViews czyta je osobno).
    fun updateAll(context: Context) {
      try {
        val mgr = AppWidgetManager.getInstance(context)
        val ids = mgr.getAppWidgetIds(ComponentName(context, ${PROVIDER_CLASS}::class.java))
        for (id in ids) updateOne(context, id)
      } catch (e: Exception) {}
    }

    // Woła się po zapisaniu configu jednej konkretnej instancji (TasksWidgetConfigActivity).
    fun updateOne(context: Context, appWidgetId: Int) {
      try {
        AppWidgetManager.getInstance(context).updateAppWidget(appWidgetId, buildViews(context, appWidgetId))
      } catch (e: Exception) {}
    }

    private fun buildViews(context: Context, appWidgetId: Int): RemoteViews {
      val views = RemoteViews(context.packageName, R.layout.tasks_widget)

      val transparent = prefs(context).getBoolean(PREF_TRANSPARENT_PREFIX + appWidgetId, false)
      if (transparent) {
        views.setInt(R.id.widget_root, "setBackgroundColor", Color.TRANSPARENT)
      } else {
        views.setInt(R.id.widget_root, "setBackgroundResource", R.drawable.widget_bg)
      }

      val openIntent = Intent(Intent.ACTION_VIEW, Uri.parse("sapp://tasks")).apply {
        setPackage(context.packageName)
      }
      val pending = PendingIntent.getActivity(
        context, 0, openIntent,
        PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
      )
      views.setOnClickPendingIntent(R.id.widget_root, pending)

      val rows = readRows(context)
      if (rows.length() == 0) {
        views.setViewVisibility(R.id.widget_empty, View.VISIBLE)
        for (i in 0 until ROWS) views.setViewVisibility(ROW_IDS[i], View.GONE)
        return views
      }
      views.setViewVisibility(R.id.widget_empty, View.GONE)

      for (i in 0 until ROWS) {
        if (i < rows.length()) {
          val row = rows.optJSONObject(i)
          if (row == null) { views.setViewVisibility(ROW_IDS[i], View.GONE); continue }
          views.setViewVisibility(ROW_IDS[i], View.VISIBLE)
          views.setTextViewText(TITLE_IDS[i], row.optString("title"))
          views.setTextViewText(SUB_IDS[i], row.optString("sub"))
          try {
            views.setInt(DOT_IDS[i], "setColorFilter", Color.parseColor(row.optString("color", "#ECEEEE")))
          } catch (e: Exception) {}
        } else {
          views.setViewVisibility(ROW_IDS[i], View.GONE)
        }
      }
      return views
    }

    private fun readRows(context: Context): JSONArray {
      return try {
        val file = File(context.filesDir, "widget_tasks.json")
        if (!file.exists()) return JSONArray()
        JSONArray(file.readText())
      } catch (e: Exception) { JSONArray() }
    }
  }
}
`;
}

function configActivityKotlin(pkg) {
  return `package ${pkg}

import android.app.Activity
import android.appwidget.AppWidgetManager
import android.os.Bundle
import android.widget.Button
import android.widget.Switch

// Auto-generated by plugins/withTasksWidget.js — do not edit here. Ekran "Edytuj widget"
// (otwiera się przy DODAWANIU widgetu — kontrakt Androida na 'android:configure', nie da się
// go inaczej ponownie otworzyć dla już umieszczonego widgetu poza usunięciem i dodaniem od
// nowa). Jedyne ustawienie na start: przezroczyste tło (2026-09-23, user: "żebym mógł
// edytować żeby np zrobić przezroczyste tło").
class ${CONFIG_CLASS} : Activity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setResult(RESULT_CANCELED)
    setContentView(R.layout.tasks_widget_config)

    val appWidgetId = intent?.extras?.getInt(
      AppWidgetManager.EXTRA_APPWIDGET_ID, AppWidgetManager.INVALID_APPWIDGET_ID,
    ) ?: AppWidgetManager.INVALID_APPWIDGET_ID
    if (appWidgetId == AppWidgetManager.INVALID_APPWIDGET_ID) { finish(); return }

    val prefs = ${PROVIDER_CLASS}.prefs(this)
    val sw = findViewById<Switch>(R.id.config_transparent_switch)
    sw.isChecked = prefs.getBoolean(${PROVIDER_CLASS}.PREF_TRANSPARENT_PREFIX + appWidgetId, false)

    findViewById<Button>(R.id.config_save_btn).setOnClickListener {
      prefs.edit().putBoolean(${PROVIDER_CLASS}.PREF_TRANSPARENT_PREFIX + appWidgetId, sw.isChecked).apply()
      ${PROVIDER_CLASS}.updateOne(this, appWidgetId)
      val result = android.content.Intent().putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID, appWidgetId)
      setResult(RESULT_OK, result)
      finish()
    }
  }
}
`;
}

function moduleKotlin(pkg) {
  return `package ${pkg}

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

// Auto-generated by plugins/withTasksWidget.js — do not edit here.
class ${MODULE_CLASS}(reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(reactContext) {
  override fun getName(): String = "TasksWidget"

  @ReactMethod
  fun requestUpdate() {
    ${PROVIDER_CLASS}.updateAll(reactApplicationContext)
  }
}
`;
}

function packageKotlin(pkg) {
  return `package ${pkg}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

// Auto-generated by plugins/withTasksWidget.js — do not edit here.
class ${PACKAGE_CLASS} : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
    listOf(${MODULE_CLASS}(reactContext))

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> =
    emptyList()
}
`;
}

function widgetRowXml(i) {
  return `    <LinearLayout
        android:id="@+id/widget_row${i}"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:gravity="center_vertical"
        android:paddingTop="3dp"
        android:paddingBottom="3dp">
        <ImageView
            android:id="@+id/widget_dot${i}"
            android:layout_width="8dp"
            android:layout_height="8dp"
            android:layout_marginEnd="8dp"
            android:src="@drawable/widget_dot_circle" />
        <TextView
            android:id="@+id/widget_title${i}"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:maxLines="1"
            android:ellipsize="end"
            android:textColor="#ECEEEE"
            android:textSize="13sp" />
        <TextView
            android:id="@+id/widget_sub${i}"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="6dp"
            android:textColor="#8A8F8F"
            android:textSize="10sp" />
    </LinearLayout>
`;
}

function widgetLayoutXml() {
  const rows = Array.from({ length: ROWS }, (_, i) => widgetRowXml(i)).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/widget_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="@drawable/widget_bg"
    android:padding="10dp">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="ZADANIA"
        android:textColor="#8A8F8F"
        android:textSize="10sp"
        android:textStyle="bold"
        android:paddingBottom="4dp" />

    <TextView
        android:id="@+id/widget_empty"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Brak zaległych zadań \u{1F389}"
        android:textColor="#ECEEEE"
        android:textSize="13sp"
        android:visibility="gone" />

${rows}
</LinearLayout>
`;
}

function widgetConfigXml() {
  return `<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="#12100F"
    android:padding="24dp">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Widget — Zadania"
        android:textColor="#ECEEEE"
        android:textSize="18sp"
        android:textStyle="bold"
        android:paddingBottom="20dp" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:gravity="center_vertical">
        <TextView
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:text="Przezroczyste tło"
            android:textColor="#ECEEEE"
            android:textSize="15sp" />
        <Switch
            android:id="@+id/config_transparent_switch"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />
    </LinearLayout>

    <Button
        android:id="@+id/config_save_btn"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="32dp"
        android:text="Zapisz" />

</LinearLayout>
`;
}

function widgetBgXml() {
  return `<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="#1A1C1C" />
    <corners android:radius="20dp" />
    <stroke android:width="1dp" android:color="#1FFFFFFF" />
</shape>
`;
}

function widgetDotXml() {
  return `<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="oval">
    <solid android:color="#FFFFFF" />
</shape>
`;
}

function widgetInfoXml() {
  // minWidth/minHeight = rozmiar POCZĄTKOWY przy dodaniu; minResizeWidth/Height = jak bardzo
  // user może go PÓŹNIEJ zmniejszyć przeciągając uchwyty (2026-09-23, user na S22 Ultra: "żeby
  // był na wysokość mniejszy jak się da" — domyślne 180dp/targetCellHeight=3 nie dawało zejść
  // niżej niż ~3 komórki siatki One UI). minResizeHeight=70dp ~ tyle co nagłówek "ZADANIA" +
  // JEDEN wiersz — najmniejszy sensowny rozmiar, reszta wierszy chowa się pod przewijaniem
  // przez usera (widget się przycina, RemoteViews nie ma innego trybu).
  return `<?xml version="1.0" encoding="utf-8"?>
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:minWidth="250dp"
    android:minHeight="140dp"
    android:minResizeWidth="140dp"
    android:minResizeHeight="70dp"
    android:targetCellWidth="4"
    android:targetCellHeight="2"
    android:updatePeriodMillis="1800000"
    android:initialLayout="@layout/tasks_widget"
    android:configure=".${CONFIG_CLASS}"
    android:resizeMode="horizontal|vertical"
    android:widgetCategory="home_screen"
    android:previewLayout="@layout/tasks_widget" />
`;
}

function withSources(config) {
  return withDangerousMod(config, ['android', async (cfg) => {
    const pkg = (cfg.android && cfg.android.package) || 'com.sokki.sapp';
    const javaDir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'java', ...pkg.split('.'));
    fs.mkdirSync(javaDir, { recursive: true });
    fs.writeFileSync(path.join(javaDir, `${PROVIDER_CLASS}.kt`), providerKotlin(pkg), 'utf8');
    fs.writeFileSync(path.join(javaDir, `${MODULE_CLASS}.kt`), moduleKotlin(pkg), 'utf8');
    fs.writeFileSync(path.join(javaDir, `${PACKAGE_CLASS}.kt`), packageKotlin(pkg), 'utf8');
    fs.writeFileSync(path.join(javaDir, `${CONFIG_CLASS}.kt`), configActivityKotlin(pkg), 'utf8');

    const resDir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res');
    const layoutDir = path.join(resDir, 'layout');
    const drawableDir = path.join(resDir, 'drawable');
    const xmlDir = path.join(resDir, 'xml');
    fs.mkdirSync(layoutDir, { recursive: true });
    fs.mkdirSync(drawableDir, { recursive: true });
    fs.mkdirSync(xmlDir, { recursive: true });
    fs.writeFileSync(path.join(layoutDir, 'tasks_widget.xml'), widgetLayoutXml(), 'utf8');
    fs.writeFileSync(path.join(layoutDir, 'tasks_widget_config.xml'), widgetConfigXml(), 'utf8');
    fs.writeFileSync(path.join(drawableDir, 'widget_bg.xml'), widgetBgXml(), 'utf8');
    fs.writeFileSync(path.join(drawableDir, 'widget_dot_circle.xml'), widgetDotXml(), 'utf8');
    fs.writeFileSync(path.join(xmlDir, 'tasks_widget_info.xml'), widgetInfoXml(), 'utf8');
    return cfg;
  }]);
}

function withManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    if (!Array.isArray(app.receiver)) app.receiver = [];
    const receiverName = `.${PROVIDER_CLASS}`;
    if (!app.receiver.some((r) => r.$ && r.$['android:name'] === receiverName)) {
      app.receiver.push({
        $: { 'android:name': receiverName, 'android:exported': 'false' },
        'intent-filter': [
          { action: [{ $: { 'android:name': 'android.appwidget.action.APPWIDGET_UPDATE' } }] },
        ],
        'meta-data': [
          { $: { 'android:name': 'android.appwidget.provider', 'android:resource': '@xml/tasks_widget_info' } },
        ],
      });
    }

    if (!Array.isArray(app.activity)) app.activity = [];
    const configName = `.${CONFIG_CLASS}`;
    if (!app.activity.some((a) => a.$ && a.$['android:name'] === configName)) {
      app.activity.push({
        $: { 'android:name': configName, 'android:exported': 'true', 'android:theme': '@android:style/Theme.DeviceDefault.Dialog.NoActionBar' },
        'intent-filter': [
          { action: [{ $: { 'android:name': 'android.appwidget.action.APPWIDGET_CONFIGURE' } }] },
        ],
      });
    }
    return cfg;
  });
}

// Rejestruje TasksWidgetPackage w getPackages() — oficjalna technika Expo (mergeContents z
// markerem, idempotentna między prebuildami) zaczepiona o standardowy podpowiadający komentarz
// który Expo zawsze generuje w MainApplication.kt.
function withPackageRegistration(config) {
  return withMainApplication(config, (cfg) => {
    cfg.modResults.contents = mergeContents({
      tag: 'sapp-tasks-widget-package',
      src: cfg.modResults.contents,
      // SDK 54 generuje `PackageList(this).packages.apply { // add(MyReactNativePackage()) }`
      // (zweryfikowane realnym `expo prebuild` — NIE starszy wzorzec `packages.add(new ...)`,
      // który jest tylko w e2e fixture innego pakietu, nie w rzeczywistym szablonie tego SDK).
      // `this` wewnątrz `.apply{}` to sama lista, więc wystarczy `add(...)` bez prefiksu.
      newSrc: `              add(${PACKAGE_CLASS}())`,
      anchor: /\/\/\s*add\(MyReactNativePackage\(\)\)/,
      offset: 1,
      comment: '              //',
    }).contents;
    return cfg;
  });
}

module.exports = function withTasksWidget(config) {
  config = withSources(config);
  config = withManifest(config);
  config = withPackageRegistration(config);
  return config;
};
