// Catches NATIVE (JVM) uncaught exceptions that a JS ErrorBoundary can't see — the
// kind that leaves a black screen with "brak zapisanego crasha". A tiny Kotlin
// ContentProvider (auto-initialised by Android before Application.onCreate) installs
// a Thread.setDefaultUncaughtExceptionHandler that writes the stack to a file in the
// app's filesDir, then delegates to the previous handler so the app still crashes as
// normal. JS reads that file on the next launch (app/_layout.tsx) and surfaces it.
//
// It re-installs itself 8s after start too, in case React Native replaced the default
// handler during init — ours re-wraps whatever is current so it stays outermost.
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const path = require('path');
const fs = require('fs');

const CLASS = 'SappCrashCatcher';

function kotlinSource(pkg) {
  return `package ${pkg}

import android.content.ContentProvider
import android.content.ContentValues
import android.database.Cursor
import android.net.Uri
import android.os.Handler
import android.os.Looper
import org.json.JSONObject
import java.io.File
import java.io.PrintWriter
import java.io.StringWriter

// Auto-generated by plugins/withNativeCrashCatcher.js — do not edit here.
class ${CLASS} : ContentProvider() {
  override fun onCreate(): Boolean {
    install()
    Handler(Looper.getMainLooper()).postDelayed({ install() }, 8000)
    return true
  }

  private fun install() {
    try {
      val ctx = context ?: return
      val prev = Thread.getDefaultUncaughtExceptionHandler()
      if (prev is SappHandler) return
      Thread.setDefaultUncaughtExceptionHandler(SappHandler(ctx.filesDir, prev))
    } catch (e: Throwable) {}
  }

  class SappHandler(private val dir: File, private val prev: Thread.UncaughtExceptionHandler?) : Thread.UncaughtExceptionHandler {
    override fun uncaughtException(t: Thread, e: Throwable) {
      try {
        val sw = StringWriter()
        e.printStackTrace(PrintWriter(sw))
        val obj = JSONObject()
        obj.put("at", System.currentTimeMillis())
        obj.put("thread", t.name)
        obj.put("message", e.toString())
        obj.put("stack", sw.toString().take(6000))
        File(dir, "native_crash.json").writeText(obj.toString())
      } catch (x: Throwable) {}
      prev?.uncaughtException(t, e)
    }
  }

  override fun query(uri: Uri, p: Array<String>?, s: String?, sa: Array<String>?, so: String?): Cursor? = null
  override fun getType(uri: Uri): String? = null
  override fun insert(uri: Uri, v: ContentValues?): Uri? = null
  override fun delete(uri: Uri, s: String?, sa: Array<String>?): Int = 0
  override fun update(uri: Uri, v: ContentValues?, s: String?, sa: Array<String>?): Int = 0
}
`;
}

function withSource(config) {
  return withDangerousMod(config, ['android', async (cfg) => {
    const pkg = (cfg.android && cfg.android.package) || 'com.sokki.sapp';
    const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'java', ...pkg.split('.'));
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, `${CLASS}.kt`), kotlinSource(pkg), 'utf8');
    return cfg;
  }]);
}

function withManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const pkg = config.android?.package || 'com.sokki.sapp';
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    if (!Array.isArray(app.provider)) app.provider = [];
    const name = `.${CLASS}`;
    if (app.provider.some((p) => p.$ && p.$['android:name'] === name)) return cfg;
    app.provider.push({
      $: {
        'android:name': name,
        'android:authorities': `${pkg}.crashcatcher`,
        'android:exported': 'false',
        'android:initOrder': '2147483647', // as early as possible
      },
    });
    return cfg;
  });
}

module.exports = function withNativeCrashCatcher(config) {
  config = withSource(config);
  config = withManifest(config);
  return config;
};
