// Udostępnij TEKST prosto do parsera paragonów (2026-09-27, user zaakceptował pomysł: "da się
// skopiowany tekst udostępnić do parsera od razu?"). `scan.tsx`'s pole "wklej tekst" już
// istnieje i już parsuje (parseReceiptText) — brakowało tylko WEJŚCIA: Android Share Sheet.
//
// TEN SAM wzorzec co withBankNotificationListener.js/withTasksWidget.js — mała, samodzielna
// natywna klasa + wpis w manifeście, ZERO dotykania MainActivity.kt (inny plugin,
// react-native-health-connect, już modyfikuje jej onCreate — nowa, osobna Activity jako
// "trampolina" unika ryzyka kolizji z tamtym mergeContents). `ShareReceiverActivity` łapie
// android.intent.action.SEND (text/plain), zapisuje tekst do pliku w filesDir (ten sam
// plik-jako-most wzorzec co bank_notifications.json/widget_toggle_queue.json — natywny kod
// PISZE, JS CZYTA), potem przekierowuje przez już zarejestrowany deep-link `sapp://` do
// /expenses/scan i się kończy (Theme.NoDisplay — brak wizualnego mrugnięcia własnego ekranu).
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const path = require('path');
const fs = require('fs');

const CLASS = 'ShareReceiverActivity';
const FILE_NAME = 'shared_receipt_text.json';

function kotlinSource(pkg) {
  return `package ${pkg}

import android.app.Activity
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import org.json.JSONObject
import java.io.File

// Auto-generated by plugins/withReceiptShareIntent.js — do not edit here.
class ${CLASS} : Activity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    try {
      if (intent?.action == Intent.ACTION_SEND && intent.type == "text/plain") {
        val text = intent.getStringExtra(Intent.EXTRA_TEXT)
        if (!text.isNullOrBlank()) {
          val obj = JSONObject()
          obj.put("text", text)
          obj.put("time", System.currentTimeMillis())
          File(filesDir, "${FILE_NAME}").writeText(obj.toString())
        }
      }
    } catch (e: Exception) {}
    try {
      val open = Intent(Intent.ACTION_VIEW, Uri.parse("sapp://expenses/scan")).apply {
        setPackage(packageName)
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
      }
      startActivity(open)
    } catch (e: Exception) {}
    finish()
  }
}
`;
}

function withSource(config) {
  return withDangerousMod(config, ['android', async (cfg) => {
    const pkg = (cfg.android && cfg.android.package) || 'com.sokki.sapp';
    const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'java', ...pkg.split('.'));
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, `${CLASS}.kt`), kotlinSource(pkg), 'utf8');
    return cfg;
  }]);
}

function withManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    if (!Array.isArray(app.activity)) app.activity = [];
    const name = `.${CLASS}`;
    if (app.activity.some((a) => a.$ && a.$['android:name'] === name)) return cfg;
    app.activity.push({
      $: {
        'android:name': name,
        'android:exported': 'true',
        // NoDisplay — ta activity nigdy nie renderuje UI, tylko zapisuje plik i
        // przekierowuje, więc nie ma czego pokazać (bez tego pojawiłby się na chwilę goły,
        // pusty ekran przed przejściem do MainActivity).
        'android:theme': '@android:style/Theme.NoDisplay',
        'android:excludeFromRecents': 'true',
      },
      'intent-filter': [
        {
          action: [{ $: { 'android:name': 'android.intent.action.SEND' } }],
          category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
          data: [{ $: { 'android:mimeType': 'text/plain' } }],
        },
      ],
    });
    return cfg;
  });
}

module.exports = function withReceiptShareIntent(config) {
  config = withSource(config);
  config = withManifest(config);
  return config;
};
